[project]
name = "deep-4-all"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo[mcp,recommended]>=0.19.2",
    "matplotlib>=3.10.8",
    "scikit-learn>=1.8.0",
    "transformers>=4.57.5",
]
