adapter_name_or_path: C:\dev\deep_4_all\cours\TP\tp4\checkpoints\csqa_stage1
bf16: true
cutoff_len: 2048
dataset: csqa_stage2
dataset_dir: C:\dev\deep_4_all\cours\TP\tp4\configs
do_train: true
finetuning_type: lora
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 0.0001
logging_steps: 10
lora_alpha: 32
lora_rank: 16
lora_target: all
model_name_or_path: unsloth/Qwen3-4B-Instruct-2507-unsloth-bnb-4bit
num_train_epochs: 3
output_dir: C:\dev\deep_4_all\cours\TP\tp4\checkpoints\csqa_stage2
per_device_train_batch_size: 2
report_to: none
save_steps: 100
stage: sft
template: qwen
